function [out1,out2] = modginput(arg1,strpointertype)

out1 = [];
out2 = [];

y = [];

fig = gcf;
figure(gcf);

how_many = arg1;
b = [];

% Suspend axes functions
state = uisuspend(fig);
set(gcf,'pointer',strpointertype); 
fig_units = get(fig,'units');
char = 0;

for i= 1:how_many
    waserr = 0;
    try
        keydown = wfbp;
    catch
        waserr = 1;
    end

    if(waserr == 1)
        if(ishandle(fig))
            set(fig,'units',fig_units);
            uirestore(state);
            error('Interrupted');
        else
            error('Interrupted by figure deletion');
        end
    end

    scrn_pt = get(0, 'PointerLocation');
    set(fig,'units','pixels')
    loc = get(fig, 'Position');
    pt = [scrn_pt(1) - loc(1), scrn_pt(2) - loc(2)];
    set(fig,'CurrentPoint',pt);

    pt = get(gca, 'CurrentPoint');

    out1 = [out1;pt(1,1)];
    y = [y;pt(1,2)];

end
% end

uirestore(state);
set(fig,'units',fig_units);

if nargout > 1
    out2 = y;
else
    out1 = [out1 y];
end


%% Wait for button press
function key = wfbp
%WFBP   Replacement for WAITFORBUTTONPRESS that has no side effects.
fig = gcf;
current_char = [];
% Now wait for that buttonpress, and check for error conditions
waserr = 0;
try
    h=findall(fig,'type','uimenu','accel','C');   % Disabling ^C for edit menu so the only ^C is for
    set(h,'accel','');                            % interrupting the function.
    keydown = waitforbuttonpress;
    current_char = double(get(fig,'CurrentCharacter')); % Capturing the character.
    if~isempty(current_char) & (keydown == 1)           % If the character was generated by the
  	  if(current_char == 3)                       % current keypress AND is ^C, set 'waserr'to 1
          waserr = 1;                             % so that it errors out.
      end
    end

    set(h,'accel','C');                                 % Set back the accelerator for edit menu.
catch
    waserr = 1;
end
drawnow;
if(waserr == 1)
    set(h,'accel','C');                                % Set back the accelerator if it errored out.
    error('Interrupted');
end
if nargout>0, key = keydown; end
